#!/bin/bash
#==============================================================================
# script de configuracao do arquivo sources.list
# e atualizacao de pacotes
# autor: 2sgt juscelino
# data: 03/09/2015
# data de modificacao: 03/09/2015
#==============================================================================